### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by marijanbrvar** [moise10r/Awesome_Book#5]

**Comment by vladanvi99** [comment]
Good job @marijanbrvar, your code looks very nice and clean. 💯 🥇

**Comment by Greg0109** [comment]
Impressive how you've managed to use as much javascript as possible instead of plain HTML or CSS @marijanbrvar

**Comment by elisha2kyakpo1** [comment]
Impressive! I like the UI.💪
